### ISSUE TITLE
No ReverseMatch at Finalize

### ISSUE THREAD

**Issue by wishabhilash** [Shopify/shopify_django_app#13]
NoReverseMatch at /shopify/finalize/
Reverse for 'root_path' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method: GET
Request URL:    http://localhost:8000/shopify/finalize/?code=dddd8e22f4a1f0195673a586c034c326&shop=log-horizon-2.myshopify.com&timestamp=1412929222&signature=c4d2343d79bdc76125a78451f8e898fd
Django Version: 1.6.6
Exception Type: NoReverseMatch
Exception Value:  
Reverse for 'root_path' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location: /usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 456
Python Executable:  /usr/bin/python
Python Version: 2.7.6
Python Path:  
['/home/wish/djangoProjects/ip_loc',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Server time:    Fri, 10 Oct 2014 08:20:24 +0000
Traceback Switch to copy-and-paste view

/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, _callback_args, *_callback_kwargs) ...
▶ Local vars
/home/wish/djangoProjects/ip_loc/shopify_app/views.py in finalize
    response = redirect(_return_address(request)) ...
▶ Local vars
/home/wish/djangoProjects/ip_loc/shopify_app/views.py in _return_address
    print "_return_address:",request.session.get('return_to') or reverse('root_path') ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, _args, *_kwargs)) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix
                             (lookup_view_s, args, kwargs, len(patterns), patterns)) ...
▶ Local vars

**Comment by Cheffheid** [comment]
I was running into this as well, but was able to resolve this. For anyone that also runs across this:

After the authentication is finalised, it tries to return you _somewhere_. This is either the `return_to` that's stored in the session, or a URL in your app with the name `root_path`.

If neither is set, you'll run into this error - because Django won't know where to send you.

**Comment by tanema** [comment]
The app has been rewritten so this issue is out of date
