### ISSUE TITLE
   Middleware  'shopify_app.middleware.LoginProtection',?

### ISSUE THREAD

**Issue by danielmcquillen** [Shopify/shopify_django_app#16]
The demo app includes the following line in MIDDLEWARE_CLASSES

```
    'shopify_app.middleware.LoginProtection',
```

However I don't see that class in the django-shopify-auth application and I get a 'No module named shopify_app.middleware' if I include it in my settings.

Was this file removed from your library?

**Comment by hockeybuggy** [comment]
Hey @danielmcquillen If you are still wondering about that [it's here]( https://github.com/Shopify/shopify_django_app/blob/d152ab48cbdf3df6c4c9accf9e773191c1fc60e5/shopify_app/middleware.py#L8) Rather than in the `shopify` library.

Does that help?

**Comment by tanema** [comment]
The app has been rewritten so this issue is out of date
