### ISSUE TITLE
 I cant get passed "syncdb" step

### ISSUE THREAD

**Issue by medyagh** [Shopify/shopify_django_app#19]
Hi I am following the tutorial step by step from scratch and I cant get passed this step:

```
$ python manage.py syncdb
Unknown command: 'syncdb'
Type 'manage.py help' for usage.
```

**Comment by aorzh** [comment]
Try
$ python manage.py makemigrations
$  python manage.py migrate

Also you will need update all urls files and as I see when you will done with this you will get other error:
File "/Users/alex/Python-scripts/shop/shopify_app/middleware.py", line 5, in <module>
    class ConfigurationError(StandardError):
NameError: name 'StandardError' is not defined

**Comment by aorzh** [comment]
@medyagh , I made a fork and added Django 1.11 support. Will working on this today and later will do a pull request.
https://github.com/aorzh/shopify_django_app

**Comment by medyagh** [comment]
thanks @aorzh

**Comment by edomario** [comment]
Use **python manage.py makemigrations**
and **python manage.py migrate**

**Comment by tanema** [comment]
The app has been rewritten so this issue is out of date
