### ISSUE TITLE
I was redirected to this page after clicking 'Get'. when  app listing

### ISSUE THREAD

**Issue by parkhya-android** [Shopify/shopify_django_app#20]
I was unable to install your app from the App Store listing. I was redirected to this page after clicking 'Get'. When clicking on 'Get' from the app listing, the app should immediately authenticate using OAuth.
 
the app has been refused for that reason, what exactly they are asking?

**Comment by jamiemtdwyer** [comment]
This repo is for the Django framework used to build Shopify apps. Please only open issues regarding this framework.
