### ISSUE TITLE
can't install dev shop in locally running app

### ISSUE THREAD

**Issue by RandomDude123** [Shopify/shopify_django_app#21]
Trying to make the example app working. Using the Django 1.11 supported version from here [https://github.com/aorzh/shopify_django_app](url).
When i go to http://localhost:8000/login/ and enter the url of my dev test shop - nothing happens. 
I added the API key & API secret key of my app in the shopify_settings.py as described.
screenshot shopify partner app: https://i.imgur.com/ERdsroi.png
test shop domain (that i use for installing the example app): https://******.myshopify.com/
What am i doing wrong here?

**Comment by tanema** [comment]
The app has been rewritten so this issue is out of date
