### ISSUE TITLE
Can't get past syncdb "KEY ERROR"

### ISSUE THREAD

**Issue by aromeoes** [Shopify/shopify_django_app#26]
Hi all, trying to follow the tutorial, and in the 
python manage.py syncdb step I get the following message:KeyError: 'DJANGO_SECRET'

Full response here:

>  python manage.py syncdb
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "C:\Python\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "C:\Python\lib\site-packages\django\core\management\__init__.py", line 325, in execute
>     settings.INSTALLED_APPS
>   File "C:\Python\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
>     self._setup(name)
>   File "C:\Python\lib\site-packages\django\conf\__init__.py", line 44, in _setup
>     self._wrapped = Settings(settings_module)
>   File "C:\Python\lib\site-packages\django\conf\__init__.py", line 107, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "C:\Python\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Users\arome\desktop\Tooles\shopify_django_app-master\settings.py", line 67, in <module>
>     SECRET_KEY = os.environ['DJANGO_SECRET']
>   File "C:\Python\lib\os.py", line 678, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'DJANGO_SECRET'
>

**Comment by abhinavpanse** [comment]
I am getting the same error. Have you found the solution?
`
  File "D:\sprct\gthb\shopify_django_app\settings.py", line 67, in <module>
    SECRET_KEY = os.environ['DJANGO_SECRET']
  File "C:\Users\abhin\.virtualenvs\shopify_django_app-mEozDe3p\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'DJANGO_SECRET'
`

**Comment by AlejandroRomeo** [comment]
Unfortunately I haven't been able to..
Would appreciate if somebody could help us still.

**Comment by abhinavpanse** [comment]
I solved it by replacing SECRET_KEY to 
SECRET_KEY = '5%y6rwwd=a@&q*x=dpo&2%fuvhl3#og_+ircxyy)u3w9x8vsqh'

**Comment by tanema** [comment]
The app has been rewritten so this issue is out of date
