### ISSUE TITLE
Does auth work?

### ISSUE THREAD

**Issue by shaohua** [Shopify/shopify_django_app#28]
tried to install but can't pass auth
running into this
```
<urlopen error unknown url type: https>
```

if I add two prints statements here
```
try:
        shop_url = params['shop']
        session = _new_session(shop_url)
        request.session['shopify'] = {
            "shop_url": shop_url,
            "access_token": session.request_token(request.GET)
        }
    except Exception as e:
        print("error")
        print(e)
        messages.error(request, "Could not log in to Shopify store.")
        return redirect(reverse(login))
```

is auth working right now?

python 3.7
a regular pip env install after removing the pip lock

**Comment by shaohua** [comment]
P.S. thanks for resume working on this

**Comment by tanema** [comment]
It has worked for me without issue, I did a quick google search and it seems like that error pops up often if you need to install openssl 
https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https

**Comment by tanema** [comment]
@shaohua Did you get this working?
