### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Seifollahi** [Shopify/shopify_django_app#32]
It would be easier to get started with this app if the "requirement.txt" file provided.
Thanks

**Comment by pmuens** [comment]
Just another addition that one can use something like this to generate a `requirements.txt` via `pipenv` --> https://github.com/pypa/pipenv/issues/3493#issuecomment-511690036

**Comment by tanema** [comment]
Thanks @pmuens for pointing to great sources. I have added the file and updated the readme to be a bit more clear.
