### ISSUE TITLE
Setup Environment

### ISSUE THREAD

**Issue by jadocoder** [Shopify/shopify_django_app#35]
Hello,
Are there some missing steps in the setup environment? I can't run 'printf' in the command line. I am running windows 10 cmd.

Thank you

**Comment by pmuens** [comment]
Hey @jadocoder,
there's no necessity to run `printf` what you're actually doing is generating a random string which is set as the `DJANGO_SCRET` environment variable. Here's an example;

```
# .env

# ...
DJANGO_SECRET=r4nd0mlyg3n3r4t4d
```

You could use a tool such as https://passwordsgenerator.net/ to generate that string.
