### ISSUE TITLE
Pure Noob Question about an error while first starting the app.

### ISSUE THREAD

**Issue by paglagayok** [Shopify/shopify_django_app#48]
Thank you developers for this first of all. Now the problem is I have getting this error while starting the app for the first time. 

`SHOPIFY_API_KEY and SHOPIFY_API_SECRET must be set in ShopifyAppConfig`

I put a .env file in the root, generated a secret key. Then why is it still showing this error?

I came accross this bit in the shopify_apps dir in the middleware. 

`        if not self.api_key or not self.api_secret:
            raise ConfigurationError("SHOPIFY_API_KEY and SHOPIFY_API_SECRET must be set in ShopifyAppConfig")`

But it seems I did put in an env file in the root along with manage.py so why?

**Comment by zarifaziz** [comment]
was this answered? I'm having the same problem
