### ISSUE TITLE
Authentication not working: 'no such table: django_session'

### ISSUE THREAD

**Issue by bencarafa** [Shopify/shopify_django_app#50]
Hi, I'm trying to login into my store in order to test the app. I followed the given instructions and tried to log into my store via .../shopify/login/, but when it redirects to .../shopify/authenticate/ I get the following error: no such table: django_session.
What could it be? thanks!

**Comment by jordanmaurice** [comment]
It was missed in the README, but there is a step you need to run before python manage.py runserver, which is to run the migrate command which creates those tables.  So run python manage.py migrate first and then runserver, that should clear the error.
