### ISSUE TITLE
Oauth Error: Oauth not supported by the Shopify API

### ISSUE THREAD

**Issue by agconti** [Shopify/shopify_django_app#6]
Problem:
I've been trying to install and run this repo, but I've run into this error when trying to install my app to my store:

```
Invalid request: The Shopify API application does not support `oauth`
```

**Has anyone been able to get a Shopify Store working with Django and Python?**

**_If so how did you get around the oauth issue?**_

Additional thoughts: 
My initial suspicion is that the repo hasn't been updated to support `oauth2.0` but the Shopify API has.  After looking through the codebase to see if can manually update to `oauth2.0` I only found a few references to oauth in the _shoify api_, and they all seem to be updated for oauth2.0 (see below). So I believe the problem must be with the API its self and not the example.  Strangely though, If I use the plain python API, everything works fine. 

```
shopify/session.py:
   50  
   51          if params.has_key('code'):
   52:             # OAuth2
   53              self.token = self.request_token(params['code'])
   54          else:
   ..
   61          shop_url = cls.__prepare_url(shop_url)
   62          if scope:
   63:             # OAuth2
   64              query_params = dict(client_id=cls.api_key, scope=",".join(scope))
   65              if redirect_uri: query_params['redirect_uri'] = redirect_uri
   66:             return "%s://%s/admin/oauth/authorize?%s" % (cls.protocol, shop_url, urllib.urlencode(query_params))
   67          else:
   68              # Legacy
   ..
   83          site = "%s://%s" % (self.protocol, self.url)
   84          params = (self.api_key, self.secret, code)
   85:         access_token_path = "/admin/oauth/access_token?client_id=%s&client_secret=%s&code=%s" % params
   86          connection = ShopifyConnection(site, None, None, ShopifyResource.timeout, JSONFormat)
   87          response = connection.post(access_token_path, ShopifyResource.headers)
```

**Comment by AhmadManzoor** [comment]
@agconti How did you solve it for private app?
