### ISSUE TITLE
UnauthorizedAccess when the user uninstalls the app

### ISSUE THREAD

**Issue by NathanSmeltzer** [Shopify/shopify_django_app#62]
Detailed error:
`pyactiveresource.connection.UnauthorizedAccess: Response(code=401, body="b'{"errors":"[API] Invalid API key or access token (unrecognized login or wrong password)"}'"`

This is the same issue as #37, but it was closed without a detailed resolution.
I believe the solution is registering an app/uninstalled [webhook](https://shopify.dev/api/admin-rest/2022-10/resources/webhook).

However, what's the best way to implement webhooks within this Django app? Can webhooks be implemented in this example app repo? Or is anyone else willing to share how they did this?

The closest solution I found is [django-shopify-webhook](https://github.com/discolabs/django-shopify-webhook), but it seems like a lot of code just to register a single webhook.

**Comment by builescudaniel** [comment]
Hi, I tried hard to do what you wrote here, but it still doesn't work. Do you think you could put a repo? or elaborate more. Thanks a lot.

**Comment by echicdesign** [comment]
thank you!
