### ISSUE TITLE
TypeError at /login/finalize/

### ISSUE THREAD

**Issue by JoeReis** [Shopify/shopify_django_app#7]
This issue occurs when the store logs in and tries to add the app.

Note: I'm using Django 1.6.2, Python 2.7.6

Stacktrace:

`TypeError at /login/finalize/
MergeDict(<QueryDict: {}>, <QueryDict: {u'shop': [u'kens-awesome-bait-shop.myshopify.com'], u'timestamp': [u'1396745815'], u'code': [u'29811f0f04e620c472b65c86cb462e42'], u'signature': [u'f9a4575c70d0d7d4bf15e2b10856d875']}>) is not JSON serializable
Request Method: GET
Request URL:    http://localhost:8000/login/finalize/?code=29811f0f04e620c472b65c86cb462e42&shop=kens-awesome-bait-shop.myshopify.com&timestamp=1396745815&signature=f9a4575c70d0d7d4bf15e2b10856d875
Django Version: 1.6.2
Exception Type: TypeError
Exception Value:    
MergeDict(<QueryDict: {}>, <QueryDict: {u'shop': [u'kens-awesome-bait-shop.myshopify.com'], u'timestamp': [u'1396745815'], u'code': [u'29811f0f04e620c472b65c86cb462e42'], u'signature': [u'f9a4575c70d0d7d4bf15e2b10856d875']}>) is not JSON serializable
Exception Location: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py in default, line 184
Python Executable:  /Users/josephreis/ENV/django_python2.7.6/bin/python
Python Version: 2.7.6
Python Path:    
['/Users/josephreis/Documents/Python/django_practice/shopify_django_app',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python27.zip',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7/plat-darwin',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7/plat-mac',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7/lib-tk',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7/lib-old',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/josephreis/ENV/django_python2.7.6/lib/python2.7/site-packages']
Server time:    Sat, 5 Apr 2014 20:00:10 -0500`

**Comment by tanema** [comment]
The app has been rewritten so this issue is out of date
